<script>
export default {
    components: {
        PageTitle: () => import('@/components/PageTitle')
    },

    head() {
        return {
            title: this.$t('Use of Cookies'),
            meta: [
                { vmid: 'description', name: 'description', content: `Conditions of Use for ${this.$store.state.ui.siteName}` }
            ]
        }
    }
}
</script>


<template>
    <div>
        <page-title>{{ $t('Use of Cookies') }}</page-title>

        <div class="pageContainerMax priv">
            <div class="priv">

                <h2>What is a cookie?</h2>
                <div class="quote mtm">
                    A cookie is a piece of information in the form of a very small text file that is placed on an internet user's hard drive.
                    It is generated by a web page server, which is basically the computer that operates a web site. The information the cookie contains
                    is set by the server and it can be used by that server whenever the user visits the site. A cookie can be thought of as an
                    internet user's identification card, which tell a web site when the user has returned.
                    <div>- <a href="http://www.aboutcookies.org/" target="_blank" class="fs12">http://www.aboutcookies.org/</a></div>
                </div>

                <div class="mtl">
                    Our site uses cookies to keep track of what items you have in your shopping cart and to remember that for when you return to our site.
                    Without these cookies the site would forget which items you have placed in your shopping cart and you would not be able to purchase any
                    products from our online store.
                </div>

                <div class="mtm">We may also collect and summarize customer information in a format that no longer identifies the individual for statistical purposes.</div>

            </div>
        </div>
    </div>
</template>


<style lang="scss">
    @import "~assets/css/components/_privacy.scss";
</style>
